version: '3.7'

services:
  nginx:
    build: containers/nginx
    volumes: 
      - public:/myapp/public
      - sockets:/myapp/tmp/sockets/
    ports:
      - '8080:80'
    depends_on:
      - rails

  rails:
    build:
      context: .
      dockerfile: "Dockerfile_${DOCKER_RAILS_ENV}"
      args:
        - SECRET_KEY_BASE=${DOCKER_SECRET_KEY_BASE}  
    image: ozroro/ozreach_rails_${DOCKER_RAILS_ENV}
    init: true
    tty: true
    volumes:
      - .:/myapp
      - public:/myapp/public
      - sockets:/myapp/tmp/sockets/
    ports:
      - "3000:3000"
    links:
      - db
      - selenium_chrome
    environment: 
      RAILS_ENV: $DOCKER_RAILS_ENV
      DB_HOST: db
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      CAPYBARA_SERVERHOST: rails
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
      RAILS_SERVE_STATIC_FILES: 
      SECRET_KEY_BASE: $DOCKER_SECRET_KEY_BASE

  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
    logging:
      driver: none

volumes:
  mysql-data:
  public:
  sockets:

