version: '3'

services:


  rails:
    image: ozroro/ozreach:latest
    tty: true
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db
      - selenium_chrome
    environment: 
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
    logging:
      driver: none



