version: '3'

services:
  nginx:
    build: containers/nginx
    volumes: 
      - public:/myapp/public:ro
    ports:
      - '8080:80'
    links:
      - rails

  rails:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec unicorn -c config/unicorn.rb -E development"
    volumes:
      - .:/myapp
      - public:/myapp/public
    ports:
      - "3000:3000"
    links:
      - db
      - selenium_chrome
    environment: 
      DB_HOST: db
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      CAPYBARA_SERVERHOST: rails
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub

  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
    logging:
      driver: none

volumes:
  mysql-data:
  public:

