FROM ozroro/ozreach_rails:base
ARG SECRET_KEY_BASE="a71082db97ca8cad38d03483c3a46ee9a2c11023920296afbf272bb78eaa1591b3c3da6bb815854afbddac97cbfb2c1733c1d0a56ba797052f879d1ed51bafd4"
ARG ROOT="/myapp"
ENV LANG=C.UTF-8TZ=Asia/Tokyo \
    RAILS_ENV="production" \
    NODE_ENV="production"
WORKDIR ${ROOT}
COPY . ${ROOT}
# RUN bundle exec rails assets:clobber
RUN SECRET_KEY_BASE=${SECRET_KEY_BASE} bundle exec rails assets:precompile && \
    yarn cache clean && \
    rm -rf node_modules tmp/cache && \
    mkdir -p tmp/pids tmp/sockets

ENTRYPOINT ["entrypoint.sh"]
CMD ["bundle", "exec", "unicorn", "-c", "config/unicorn.rb", "-E", "production"]